export interface TicketConfig { enabled:boolean; defaultCategoryId:string|null; archiveCategoryId:string|null; logChannelId:string|null; transcriptChannelId:string|null; supportRoleIds:string[]; adminRoleIds:string[]; maxOpenPerUser:number; cooldownMinutes:number; autoCloseHours:number; deleteAfterCloseMinutes:number; allowCreatorClose:boolean; requireCloseReason:boolean; transcriptOnClose:boolean; dmOnClose:boolean; feedbackEnabled:boolean; firstResponseSlaMinutes:number; namingTemplate:string; defaultPriority:"low"|"normal"|"high"|"urgent"; blacklistUserIds:string[] }
export interface TicketQuestion { id:string; label:string; placeholder:string|null; style:"short"|"paragraph"; required:boolean }
export interface TicketCategory { id:string; label:string; description:string|null; emoji:string; categoryId:string|null; supportRoleIds:string[]; priority:"low"|"normal"|"high"|"urgent"; questions:TicketQuestion[] }
export interface TicketPanel { _id:string; name:string; title:string; description:string; color:string; imageUrl:string|null; footer:string; style:"buttons"|"select"; channelId:string|null; messageId:string|null; categories:TicketCategory[]; enabled:boolean }
export interface TicketRecord { _id:string; ticketNumber:number; channelId:string|null; creatorId:string; creatorTag:string; categoryLabel:string; status:string; priority:string; claimedByTag:string|null; createdAt:string; updatedAt:string; closedAt:string|null; feedbackRating:number|null }
export interface TicketAnalytics { total:number; open:number; closed:number; avgFirstResponseMinutes:number|null; avgCloseMinutes:number|null; ratingsAverage:number|null; topCategory:string|null; staffLeaderboard:{id:string;tag:string;count:number}[] }
export interface TicketChannel { id:string; name:string; type:number; parentId:string|null }
export interface TicketRole { id:string; name:string; color:number; editable:boolean }
export interface TicketsData { config:TicketConfig; panels:TicketPanel[]; tickets:TicketRecord[]; analytics:TicketAnalytics; channels:TicketChannel[]; roles:TicketRole[] }
